version: '3.7'
#
services:
  iris:
    build:
      context: ./build
    hostname: iris

    ports:
    # superserver default port 
    - "1972:1972"
    # webserver/management portal port
    - "52773:52773"

    volumes:
    - ./cpf:/home/irisowner/cpf
    - ./iris-mgr:/iris-mgr
    - ./logs:/logs

    environment:
    - TZ=JST-9
